In [3]:
import torch
import numpy as np

In [4]:
my_list = [1,2,3,4,5]
my_list
np_arr = np.array(my_list)

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
#create tensor from np array
my_tensor = torch.tensor(np_arr)
my_tensor

tensor([1, 2, 3, 4, 5])

In [8]:
my_tensor = torch.arange(10)
my_tensor 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#reshape and view
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#reshape when we don't know number of items
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch3 = torch.arange(15)
my_torch3 = my_torch3.view(3,5) 
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [21]:
my_torch4 = torch.arange(10)
print(my_torch4)
my_torch5 = my_torch4.reshape(2,5)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [24]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [26]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [31]:
#Slices
my_torch6 = torch.arange(10)

#grab a specific item
my_torch6[7] #grabbing the tensor 7 rather than number 7

tensor(7)

In [34]:
#grab a slice 
my_torch7 = my_torch6.reshape(5,2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
 my_torch7[:, 1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#return column
my_torch7[: