In [2]:
import torch
import numpy as np

In [7]:
tensor_a  = torch.tensor([1,2,3,4])
tensor_b  = torch.tensor([5,6,7,8])

In [39]:
#addition
tensor_a+tensor_b

tensor_a.add(tensor_b)
# addition longhand
torch.add(tensor_a,tensor_b)

tensor([11, 14, 17, 20])

In [18]:
#substraction
tensor_b-tensor_a

#substraction shorthand
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [22]:
#multiplication
tensor_a*tensor_b

# multiplication longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [26]:
#division
tensor_b/tensor_a

#division longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [31]:
#remainder modulus
tensor_b % tensor_a

torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [44]:
#exponents/power
torch.pow(tensor_a,tensor_b)

tensor([      4084101,     308915776,   27512614111, 2821109907456])

In [46]:
#reassignment
# tensor_a = tensor_a+tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([31, 38, 45, 52])